---
title: "Microarray_Lecture"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Microarrays

Majority of multi-exon human genes produce more than one transcript through alternative splicing.

Expression levels of different transcripts can be measured by comparing the signal from different parts of a gene.

Probe 1 measures exon 1, probe 2 measures exon 2, probe 3 measures exon 3.

also used in molecular diagnostics -- ex) ChIP-chip. Used to find where proteins are bound to DNA.

DNA loci on microarray, fluorescent tag washed over.

Very common use: high-throughput genotyping. Trying to identify variants associated with disease phenotypes -- population studies.
Microarray contains probes corresponding to both alleles of each human SNP. Relative intensity of the signals allow SNPs to be genotyped.
**Genome-wide association studies**. 

While sequencing has replaced microarrays in many applications, there are still uses for them and it's good to know about them.

# Microarrays for Gene Expression

Measure expression level of all genes simultaneously -- whole sets of genes, not just individual genes.
mRNA is not very stable, cDNA very stable. So:

1. Choose cell populations
2. extract mRNA and reverse transcribe to cDNA
3. Fluorescent labelling of cDNAs
4. Pool samples and hybridize to the microarray
5. Scan the hybridized array
6. Interpret the scanned image

Each 'spot' is a DNA sequence called a probe. Lazer excites probes, you get fluorescent signals across the whole microarray.
Can have multiple probes with different colors -- then red spots was one probe, green was another, and yellow was both.

This is an **analog** measure -- you measure the relative fluorescence between spots.

## genechips

DNA oligonucleotides synthesized on the array. Probes usually around 25bp, classically targetted to 3' end. 
You have more than one probe (for many reasons).
**Probeset** -- collection of probes that are targeting either the entire gene or a particular feature of the gene.

## Where do we get microarray data?

If you want to publish microarray data, you must have the data publicly available.
One of the ones is GEO -- Gene Expression Omnibus. Database for microarray expression data.

**Platform** - describes the microarray
**Samples** - describes the samples
**Series** - higher order: the experiment. 

https://www.ncbi.nlm.nih.gov/geo

Example accession codes:

- GPL6244
- GSM1213927
- GSE50084
